# Generated by Django 3.2 on 2021-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bhav',
            fields=[
                ('SC_CODE', models.IntegerField(primary_key=True, serialize=False)),
                ('SC_NAME', models.CharField(max_length=100)),
                ('SC_GROUP', models.CharField(max_length=10)),
                ('SC_TYPE', models.CharField(max_length=10)),
                ('OPEN', models.CharField(max_length=100)),
                ('HIGH', models.CharField(max_length=100)),
                ('LOW', models.CharField(max_length=100)),
                ('CLOSE', models.CharField(max_length=100)),
                ('LAST', models.CharField(max_length=100)),
                ('PREVCLOSE', models.CharField(max_length=100)),
                ('NO_TRADES', models.CharField(max_length=100)),
                ('NO_OF_SHRS', models.CharField(max_length=100)),
                ('NET_TURNOV', models.CharField(max_length=100)),
                ('TDCLOINDI', models.CharField(max_length=100)),
            ],
        ),
    ]
